version: "3.8"
services:
  nginx:
    ports:
      - "5000:80"
  backendwnode:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - mynet
    environment:
      - NODE_ENV=development
      # - MONGO_USER=osman
      # - MONGO_PASSWORD=goni
    command: npm run dev
  # mongo:
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=osman
  #     - MONGO_INITDB_ROOT_PASSWORD=goni

networks:
  mynet:
    driver: bridge

