apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: backendusingnode
  # annotations:
  #   kubernetes.io/service-account.name: "sa-name"
# type: kubernetes.io/service-account-token
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  # extra: YmFyCg==
  mongo-user: dXNlcm5hbWU=
  mongo-password: cGFzc3dvcmQ=
