apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  # annotations:
  #   kubernetes.io/service-account.name: "sa-name"
# type: kubernetes.io/service-account-token
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  # extra: YmFyCg==
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
