version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mynet
  dbs:
    image: mongo
    container_name: dbs
    ports:
      - "27017:27017"
    volumes:
      - mongovol:/data/db  
    networks:
      - mynet
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisvol:/data/db
    networks:
      - mynet
  backendwnode:
    image: goniusman/backend:master-2ff56e9
    networks:
      - mynet
    environment:
      - ports=5000
      - MONGODB_local=dbs 
      - REDIS_HOST=redis
      - MONGODB_PORT=27017
      - REDIS_PORT=6379
    depends_on:
      - dbs
      - redis
volumes:
  mongovol:
  redisvol:
networks:
  mynet:
    driver: bridge