name: Update Kubernetes Manifest
on:
    repository_dispatch:
        types: [update-image-tag] # Match the event type from Repo A


jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2

      - name: Read Existing Tag from YAML
        id: read_tag
        run: |
          OLD_TAG=$(yq e '.spec.template.spec.containers[0].image' webapp.yaml)
          echo "::set-output name=old_tag::$OLD_TAG"
        working-directory: backendusingnode


      - name: Debug Tag Values
        run: |
          echo "Old tag: ${{ steps.read_tag.outputs.old_tag }}"
          echo "New tag: ${{ github.event.client_payload.tag }}"
          echo "New tag: ami osman goni...."

      - name: Update Tag in YAML
        id: update_yaml
        run: |
          sed -i "s|image: ${{ steps.read_tag.outputs.old_tag }}|image: goniusman/backend:${{ github.event.client_payload.tag }}|" webapp.yaml || echo "Failed to update YAML file"
        working-directory: backendusingnode
      


      - name: Commit and Push Updated YAML
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git add webapp.yaml
          git commit -m "Update Docker image tag dynamically"
          git push
        working-directory: backendusingnode
